"""Add not null constraints

Revision ID: 94886f55f5a1
Revises: 62443ee7d7f2
Create Date: 2024-11-01 00:16:19.901996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94886f55f5a1'
down_revision: Union[str, None] = '62443ee7d7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracked_items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tracked_items', 'current_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('tracked_items', 'target_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('tracked_items', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tracked_items', 'link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tracked_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tracked_items', 'last_checked_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracked_items', 'last_checked_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tracked_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tracked_items', 'link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tracked_items', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tracked_items', 'target_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('tracked_items', 'current_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('tracked_items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
